### ISSUE TITLE
Intensity-sum calculation

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#168]
Leah, thanks for correcting the intensity-sum calculation. Small request: I think we should change over the calculation for intensity_sum to the charge-state based one, rather than having two fields for intensity-sums, one that's unused.

**Comment by lschaffer2** [comment]
I made it a separate field because I didn't know if we wanted the "original" intensity sum value to be lost/overwritten w/ the overlapping charge states one. For example, in the original raw-exp-comps dgv or tsv file, it would show the overlapping charge states one. Minor issue, but I wasn't sure how important that original value might be. If we decide that it's unimportant, I can change it to the one intensity sum field!
