### ISSUE TITLE
Aggregated mass calculation

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#202]
I think there might be an error in the aggregated mass calculation. I'm writing a test for it, and the code doesn't make sense to me and isn't passing my test for components with differing corrected masses. 

this.agg_mass = aggregated_components.Select(p => (p.corrected_mass + Math.Round((this.root.corrected_mass - p.corrected_mass), 0) \* 1.0015) \* p.intensity_sum_olcs / this.agg_intensity).Sum();

I think the goal is to sum the corrected masses, while correcting the monoisotopic error from Thermo Deconvolution (is that error still present in v4.0?). However, it currently adds this to the new corrected mass, so I think we may be double counting the monoisotopic errors. The error I'm finding in my test is fairly small (> 1% in terms of relative error in expected vs. actual aggregated mass), but could you take a look at the logic to make sure it does what's intended?

**Comment by trishorts** [comment]
this is not my code. I will send you old code in email. Aggregation is tricky because you have to aggregated in tiny windows around a central mass. For instance, if your seed mass is 1000 and your aggregation window is 10 ppm then to aggregate two missed monoisotopics on either side along with the seed you need the following groups:
1000+/-10ppm
(1000+(1.0015)) +/- 10ppm
(1000+(2.003)) +/- 10ppm
(1000-(1.0015)) +/- 10ppm
(1000-(2.003)) +/- 10ppm

presumably this is a weighted aggregation which considers the relative intensity in calculating the group aggregated mass. Combination of all windows above will lead to a single aggregated mass.
