### ISSUE TITLE
ET and EE peak accept bool not changing the peak's relations accept bool

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/proteoform-suite#319]

**Comment by acesnik** [comment]
This gets a bit convoluted because of the inheritance... DeltaMassPeak has a peak_accepted field that indicates whether the peak was accepted. The relations it contains are all set to the peak's accepted Boolean. I wouldn't expect changing a single relation's accepted Boolean would change the peak. Would you like that to be the expected behavior; why?

**Comment by lschaffer2** [comment]
The other way -- when I unselected a peak the relations dgv didn't change

**Comment by lschaffer2** [comment]
in EE only I think

**Comment by acesnik** [comment]
Got it. Thanks for letting me know. I'll check it out.

**Comment by lschaffer2** [comment]
solved in #320
