### ISSUE TITLE
Incomplete permutation?

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/proteoform-suite#413]
With the current code, we're getting 3 permutations of the 2 conditions X 3 biological replicates. That doesn't seem right to me... Seems like it should be 5 per.

Original) {N1, N2, N3}, {S1, S2, S3}
1) {S1, S2, S3}, {N1, N2, N3} -- ignore because it will have the same test statistic as the original
2) {N1, S2, S3}, {S1, N2, N3}
3) {S1, N2, S3}, {N1, S2, N3}
4) {S1, S2, N3}, {N1, N2, S3}
5) {N1, N2, S3}, {S1, S2, N3}
6) {S1, N2, N3}, {N1, S2, S3}

**Comment by acesnik** [comment]
Oh, this is intentional because they are balanced permutations. Because we only have 3 in each set, we're limited to having the majority be from a set. Otherwise, the test statistics cancel each other out upon averaging.

{N1, S2, S3}, {S1, N2, N3}
{S1, N2, S3}, {N1, S2, N3}
{S1, S2, N3}, {N1, N2, S3}

**Comment by trishorts** [comment]
Correct. Must be even number.

On Jun 28, 2017 2:44 PM, Anthony <notifications@github.com> wrote:

Oh, this is intentional because they are balanced permutations. Because we only have 3 in each set, we're limited to having the majority be from a set. Otherwise, the test statistics cancel each other out upon averaging.

{N1, S2, S3}, {S1, N2, N3}
{S1, N2, S3}, {N1, S2, N3}
{S1, S2, N3}, {N1, N2, S3}
